#!/usr/bin/env python3
"""
AapdaSync — photograph bundler
================================================================================
Takes the photographs supplied for the record cards, downscales them, and writes
them into src/photos-bundled.js as base64 data URIs.

WHY BUNDLE RATHER THAN LOAD FROM A FOLDER
The app has to run identically from file://, from the single-file build, and
from the hosted page whose CSP blocks every external host. A data URI is the
only form that survives all three. It also means the photographs cannot go
missing: once they are in the bundle, no card can silently fall back.

SIZING
Cards render about 420x192 CSS px in a container with object-fit:cover, so the
browser is going to crop to roughly 2.19:1 and draw at about 840x384 on a 2x
display. Cropping to that ratio HERE rather than leaving it to the browser is
most of the file size: a 1000x673 frame carries 40% more rows than the card can
ever show, and those rows are paid for on every page load. Cropping first, then
sizing to 880x402 at q76, takes the set from 960 KB to under 400 KB with nothing
visible lost.

PROVENANCE
Each entry carries a `credit` string and a `verified` flag, both set in SOURCES
below rather than inferred here. An unverified photograph is still rendered —
it is the operator's build — but it is rendered with its caption visible at all
times rather than on hover, so nobody reads it as a confirmed record of the
event on that card.

Run:  python3 train/bundle_photos.py
Out:  src/photos-bundled.js
"""

import base64, io, json, os
from PIL import Image, ImageOps

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = '/mnt/user-data/uploads/tragedy_pics'

CARD_W, CARD_H, QUALITY = 880, 402, 76

# record id -> (filename, caption, credit, verified)
#
# `caption` says what the frame actually shows, which is not always the event on
# the card. Where the photograph plainly post-dates the disaster, or appears to
# show a different one, that is stated rather than smoothed over: the record
# cards are the one place in this prototype where the data is real, and a
# mislabelled photograph there costs more than a missing one.
#
# Keep captions to roughly one line. They render as a strip across the bottom of
# the card, and a three-line strip covers the photograph it is captioning.
SOURCES = {
    'R-1984': ('bhopal_gas.jpeg',
               'The abandoned Union Carbide plant, Bhopal — photographed years after 1984',
               'Supplied with this build · provenance unverified', False),
    'R-1999': ('odissha_supper cyclone .jpeg',
               'Cyclone damage in coastal Odisha — likely a later cyclone, not 1999',
               'Supplied with this build · provenance unverified', False),
    'R-2001': ('bhuj_2001.jpeg',
               'Collapsed concrete mid-rise after an earthquake — likely not Bhuj 2001',
               'Supplied with this build · provenance unverified', False),
    'R-2013': ('kedarnath_2013.jpeg',
               'The Ganga in spate, Uttarakhand — the river, not Kedarnath town',
               'Supplied with this build · provenance unverified', False),
    'R-2018': ('kerla_flood .jpeg',
               'Inundated village, Kerala floods',
               'Supplied with this build · provenance unverified', False),
    'R-2021': ('chamoli_glacier_melt .jpeg',
               'The Tapovan barrage after the 2021 Chamoli rock-ice avalanche',
               'Supplied with this build · provenance unverified', False),
}


def encode(path):
    im = Image.open(path)
    im = ImageOps.exif_transpose(im).convert('RGB')
    # Centred crop to the card ratio. Centre rather than a saliency guess: in an
    # aerial flood frame or a debris field the subject IS the whole frame, and a
    # clever crop mostly finds a reason to cut off half of it.
    im = ImageOps.fit(im, (CARD_W, CARD_H), Image.LANCZOS, centering=(0.5, 0.5))
    buf = io.BytesIO()
    im.save(buf, 'JPEG', quality=QUALITY, optimize=True, progressive=True)
    return im.size, buf.getvalue()


def main():
    out, total = {}, 0
    for rid, (fn, caption, credit, verified) in SOURCES.items():
        p = os.path.join(SRC, fn)
        if not os.path.exists(p):
            print(f'{rid:9} MISSING {fn}')
            continue
        (w, h), data = encode(p)
        total += len(data)
        out[rid] = {
            'uri': 'data:image/jpeg;base64,' + base64.b64encode(data).decode(),
            'caption': caption, 'credit': credit, 'verified': verified,
            'w': w, 'h': h, 'file': fn,
        }
        print(f'{rid:9} {w}x{h}  {len(data)/1024:6.1f} KB   {fn}')

    body = ',\n'.join('  %s: %s' % (json.dumps(k), json.dumps(v)) for k, v in out.items())
    js = (
        '/* AapdaSync — photos-bundled.js  (GENERATED by train/bundle_photos.py)\n'
        '   Photographs supplied for the record cards, downscaled and inlined so they\n'
        '   survive the folder build, the single-file build and the hosted page alike.\n'
        '   Each carries the caption and credit set in that script. Entries with\n'
        '   verified:false keep their caption on screen at all times. */\n'
        "'use strict';\n"
        'var PHOTO_IMG = {\n' + body + '\n};\n'
    )
    path = os.path.join(ROOT, 'src', 'photos-bundled.js')
    with open(path, 'w') as f:
        f.write(js)
    print(f'\nwrote src/photos-bundled.js  {os.path.getsize(path)/1024:.1f} KB '
          f'({len(out)} photographs, {total/1024:.0f} KB of JPEG)')


if __name__ == '__main__':
    main()
