/* ============================================================================
   AapdaSync — forecast.js
   ---------------------------------------------------------------------------
   Runs the trained model in the browser and, for every number it produces,
   can say which feature produced it.

   The model is a logistic regression, which is not a fashionable choice. It is
   the right one here: the contribution of each feature to a prediction is
   exactly coef × z, so "Why this score?" is arithmetic rather than an
   approximation. A gradient-boosted model would score a little higher and
   would not be able to answer the question an officer will actually ask.

   Weights come from src/model.js, generated by train/train_forecast.py.
   ========================================================================== */

'use strict';

var FORECAST = (function () {

  function sig(z) { return 1 / (1 + Math.exp(-z)); }

  /* Fast and slow antecedent-precipitation stores, the same recursion the
     training script used. Rebuilt from the bundled rainfall window. */
  function stores(rain, upto) {
    var a7 = 0, a30 = 0;
    for (var i = 0; i <= upto && i < rain.length; i++) {
      a7 = 0.80 * a7 + rain[i];
      a30 = 0.955 * a30 + rain[i];
    }
    return { api7: a7, api30: a30 };
  }

  function seasonAt(doy) {
    var d = ((doy % 365) + 365) % 365;
    return Math.exp(-0.5 * Math.pow((d - 205) / 46.0, 2));
  }

  /* Build the 15-vector for one habitation on one day of the bundled window. */
  function featuresFor(habId, dayIdx) {
    var W = MODEL.weather, rain = W.rain_mm;
    var idx = dayIdx == null ? rain.length - 1 : Math.max(0, Math.min(rain.length - 1, dayIdx));
    var s = stores(rain, idx);
    var doy = W.doy - (rain.length - 1 - idx);
    var st = MODEL.static[habId];
    if (!st) return null;
    var rain1 = idx > 0 ? rain[idx - 1] : 0;
    var rain3 = Math.max(rain[idx], idx > 0 ? rain[idx - 1] : 0, idx > 1 ? rain[idx - 2] : 0);
    var since = daysSince(habId) / 400;
    return [
      s.api7, s.api30, rain1, rain3, seasonAt(doy),
      st[0], st[1], st[2], st[3], st[4],
      st[5], st[6], since,
      (s.api7 / 100) * (st[3] / 5), (s.api7 / 100) * st[1]
    ];
  }

  /* Days since this habitation was last impacted. Derived from the declared
     events rather than invented: a habitation whose dominant hazard is live
     was impacted today. */
  function daysSince(habId) {
    var h = (ENG.STATE.habs || []).filter(function (x) { return x.id === habId; })[0];
    if (!h) return 400;
    var w = ENG.windowInfo(h);
    if (w.ongoing) return 0;
    if (h.HEI.score >= 70) return 30;
    if (h.HEI.score >= 45) return 120;
    return 320;
  }

  function predict(habId, dayIdx) {
    var x = featuresFor(habId, dayIdx);
    if (!x) return null;
    var z = 0, parts = [];
    for (var i = 0; i < x.length; i++) {
      var zi = (x[i] - MODEL.mean[i]) / MODEL.scale[i];
      var c = MODEL.coef[i] * zi;
      z += c;
      parts.push({ f: MODEL.features[i], raw: x[i], z: zi, contribution: c, coef: MODEL.coef[i] });
    }
    z += MODEL.intercept;
    var p = sig(z);
    parts.sort(function (a, b) { return Math.abs(b.contribution) - Math.abs(a.contribution); });

    /* Extrapolation guard, against the observed training range rather than a
       fixed z-threshold. A monsoon day legitimately sits at z≈3.7 on antecedent
       rainfall and the model was fitted on hundreds of them; flagging every one
       of those would teach an operator to ignore the flag entirely. What matters
       is whether a feature has left the range the model actually saw. */
    var far = parts.filter(function (q) {
      var i = MODEL.features.indexOf(q.f);
      if (i < 0 || !MODEL.zmin) return false;
      return q.z < MODEL.zmin[i] - 0.25 || q.z > MODEL.zmax[i] + 0.25;
    });
    return { p: p, logit: z, parts: parts, extrapolating: far.length > 0, farFeatures: far.map(function (q) { return q.f; }) };
  }

  /* Trend: today against a week ago, measured on the LOG-ODDS rather than the
     probability. At the top of the scale probability cannot move — a habitation
     going from 0.985 to 0.997 is a real deterioration that a probability delta
     reports as 0.01 and calls "stable". The logit has room at both ends. */
  function trend(habId) {
    var n = MODEL.weather.rain_mm.length;
    var now = predict(habId, n - 1), then = predict(habId, n - 8);
    if (!now || !then) return null;
    var dz = now.logit - then.logit;
    return {
      delta: now.p - then.p, dz: dz, now: now.p, before: then.p,
      label: dz > 0.35 ? 'Worsening' : (dz < -0.35 ? 'Improving' : 'Stable')
    };
  }

  /* Fourteen-day trajectory under three rainfall scenarios. The scenarios are
     labelled because they are assumptions, not forecasts. */
  var SCENARIOS = [
    { id: 'dry', label: 'Dry spell', mm: 0, note: 'no further rain' },
    { id: 'normal', label: 'Seasonal normal', mm: null, note: 'recent 14-day mean continues' },
    { id: 'wet', label: 'Sustained heavy rain', mm: 55, note: '55 mm/day sustained' }
  ];

  function trajectory(habId, scenarioId, days) {
    days = days || 14;
    var W = MODEL.weather, base = W.rain_mm.slice();
    var recent = base.slice(-14);
    var mean = recent.reduce(function (a, b) { return a + b; }, 0) / recent.length;
    var sc = SCENARIOS.filter(function (s) { return s.id === scenarioId; })[0] || SCENARIOS[1];
    var add = sc.mm == null ? mean : sc.mm;
    var series = base.concat();
    for (var d = 0; d < days; d++) series.push(add);

    var saved = MODEL.weather.rain_mm;
    MODEL.weather.rain_mm = series;
    var out = [];
    for (var i = 0; i < days; i++) {
      var r = predict(habId, base.length + i);
      out.push({ day: i + 1, p: r ? r.p : 0 });
    }
    MODEL.weather.rain_mm = saved;
    return { scenario: sc, points: out };
  }

  /* District roll-up: every habitation, ranked by seven-day probability. */
  function board() {
    return (ENG.STATE.habs || []).map(function (h) {
      var r = predict(h.id), t = trend(h.id);
      return {
        hab: h, p: r ? r.p : 0, parts: r ? r.parts : [],
        extrapolating: r ? r.extrapolating : false,
        trend: t, expected: (r ? r.p : 0) * h.pop,
        confidence: confidenceFor(r ? r.p : 0, r)
      };
    }).sort(function (a, b) { return b.p - a.p; });
  }

  /* Confidence is not invented. It is read off the held-out reliability table:
     for the bin this prediction falls into, how close was predicted to
     observed, and on how many held-out cases. A bin with no support returns
     "unsupported" rather than a number. */
  function confidenceFor(p, r) {
    var rel = MODEL.reliability || [];
    var b = null;
    for (var i = 0; i < rel.length; i++) {
      if (Math.abs(rel[i].bin - p) <= 0.05) { b = rel[i]; break; }
    }
    if (!b) return { label: 'Unsupported', level: 'off', why: 'No held-out cases fell in this probability band, so calibration here is unverified.' };
    if (r && r.extrapolating) return { label: 'Extrapolating', level: 'warn', why: 'Conditions lie outside the range the model was fitted on (' + r.farFeatures.join(', ') + ').' };
    var gap = Math.abs(b.predicted - b.observed);
    if (gap <= 0.05) return { label: 'Good', level: 'ok', n: b.n, why: 'In this band the model predicted ' + Math.round(b.predicted * 100) + '% and ' + Math.round(b.observed * 100) + '% actually occurred, over ' + b.n + ' held-out cases.' };
    if (gap <= 0.12) return { label: 'Fair', level: 'inf', n: b.n, why: 'In this band the model predicted ' + Math.round(b.predicted * 100) + '% against ' + Math.round(b.observed * 100) + ' observed, over ' + b.n + ' held-out cases.' };
    return { label: 'Poor', level: 'warn', n: b.n, why: 'The model is miscalibrated in this band: predicted ' + Math.round(b.predicted * 100) + '%, observed ' + Math.round(b.observed * 100) + '%, over ' + b.n + ' cases.' };
  }

  /* Bands are set where they separate this district, not at round numbers. In
     the monsoon window almost everything clears 60%, so a 60% cut would print
     "very likely" twenty times and rank nothing. */
  function band(p) {
    if (p >= 0.85) return { k: 'crit', label: 'Very likely' };
    if (p >= 0.55) return { k: 'high', label: 'Likely' };
    if (p >= 0.25) return { k: 'med', label: 'Possible' };
    return { k: 'low', label: 'Unlikely' };
  }

  return {
    predict: predict, trend: trend, trajectory: trajectory, board: board,
    band: band, featuresFor: featuresFor, confidenceFor: confidenceFor,
    SCENARIOS: SCENARIOS, seasonAt: seasonAt
  };
})();
